//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputActions/RtsInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RtsInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RtsInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RtsInputActions"",
    ""maps"": [
        {
            ""name"": ""Groups"",
            ""id"": ""9e12ac19-436a-47a4-9023-8bebeeb80d35"",
            ""actions"": [
                {
                    ""name"": ""InteractToGroup"",
                    ""type"": ""Value"",
                    ""id"": ""b66cd365-7524-4633-829f-03667993408c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AddToGroupState"",
                    ""type"": ""PassThrough"",
                    ""id"": ""33039073-d9d5-4819-ab5f-17f74bebc092"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetGroupState"",
                    ""type"": ""PassThrough"",
                    ""id"": ""82fecd51-a04b-4ce0-bce5-88ab16d575ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1cc39a9d-8541-4d00-9928-4e2c871b6ea8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8d76138-aeb0-42ba-ab70-97fa8a6fde77"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f46cb43f-ee14-483f-85be-727cdbced070"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5aaa55d4-0eb5-4994-ac5f-c4c4631df52d"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fc82188-b7d1-4a67-a076-065ef5d2f8e5"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=5)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb88897f-3a30-4ef9-872a-dace96edd1f6"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=6)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3276b67a-9be0-4128-95a6-c9e33a75d21b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=7)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""740c18ea-603d-4623-b51c-ecca04e0ce2d"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fae1d088-071f-4f91-94b0-d338fb06e201"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=9)"",
                    ""groups"": """",
                    ""action"": ""InteractToGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""839d0f25-d4db-4298-be85-d8545b4cc2b5"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddToGroupState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""394b45e1-3f6d-477d-a159-c5d8c3895416"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetGroupState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""41230f96-efb3-4af3-872f-c27c7f3b9081"",
            ""actions"": [
                {
                    ""name"": ""Pan"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2434025a-8bfb-42f9-a95e-ace4723912b6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6a06b00b-2d1f-4a1a-97f0-3c092df48c63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AltState"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd24b31e-c6eb-4560-b157-b801afb1c5fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe9645ba-a142-4f53-b6f2-ca770f6c039c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ff397edf-b0d3-460e-9bf6-c3257ba09295"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b295737c-d211-468f-aa76-5773d5bf6742"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""41913688-6b05-4148-8033-825c0210ca0a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3fb76139-e878-4064-9212-52fe948bf3af"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""473e19e1-e734-4976-8441-af5815a99c47"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b442720a-4fdc-4450-b9c6-f3288ade5d8a"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnScreenInteraction"",
            ""id"": ""4383e8bd-d797-4141-8f1c-cb49dd05a4be"",
            ""actions"": [
                {
                    ""name"": ""BeginDrag"",
                    ""type"": ""Button"",
                    ""id"": ""ddeb5d47-9d62-46c1-b53e-bebfb6ff7426"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""7c924dd8-46b3-4683-8de0-475c8c3ff8e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(pressPoint=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""3aa29851-920e-47fe-bc83-37a402da7aab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1d2a0b5a-9554-4734-a361-8ff9c06879f2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftMod"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b83ea040-4b3f-423c-afa3-92dddb3be034"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""88150707-cee4-4013-af00-ac6d5cb61451"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollGroup"",
                    ""type"": ""Button"",
                    ""id"": ""01c213ff-34fc-4e73-bd57-429cf44aa636"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bc751bbb-198e-430f-a8b7-739191980e1d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38ff9a77-2441-43d5-8c2a-c1273ad06fd9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9818806b-0545-446f-84ae-f39b5aff26f3"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftMod"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc5c2094-6b79-4b4f-a31e-1b10545ae7d0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e3edfca-e0cf-4659-a50a-3cf304381ae5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BeginDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2246c73c-c22a-4ea2-b3be-cae8d54d7272"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a657e41a-6471-44c1-b01a-07de4740808f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Bindings"",
            ""id"": ""4fade705-cbd9-4cfd-bba1-246a6daee203"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""1643ccd8-c701-4c02-bfd2-05c342f422c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""fb933abc-b5dd-45f9-8740-154ae7d19d24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attach"",
                    ""type"": ""Button"",
                    ""id"": ""7cd27f06-3b05-4d93-89b0-7c0b1e1f2eeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d27e495d-04ad-4062-8fd0-bfab3c96d65f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetIdleStrategy"",
                    ""type"": ""Button"",
                    ""id"": ""cc6d6186-59d8-491b-b6a7-ce5e87183cfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetAggressiveStrategy"",
                    ""type"": ""Button"",
                    ""id"": ""8d6ad90d-2950-41a2-9e41-961edb79c967"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetDefenciveStrategy"",
                    ""type"": ""Button"",
                    ""id"": ""297a5143-2216-4f3a-9f61-3baf25bd2218"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueWorkerUnit"",
                    ""type"": ""Button"",
                    ""id"": ""e6cfffdd-4bd6-4874-87e9-da0e54ea7a14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeWorkers"",
                    ""type"": ""Button"",
                    ""id"": ""fe8cb88d-7a0e-46e1-a120-3eed42a40f7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CollectWorkers"",
                    ""type"": ""Button"",
                    ""id"": ""b8d1d19b-eae4-4aeb-b9aa-c3b3f37a4acf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""939daa26-213d-4d7f-b84e-3f9c5cc70b02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueMeleeWarrior"",
                    ""type"": ""Button"",
                    ""id"": ""6cf219be-7655-4f56-afeb-abceb0a51ac8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueRangedWarrior"",
                    ""type"": ""Button"",
                    ""id"": ""c8834cf9-660f-454b-92ec-b3e0c4d3bb6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueBuildingAttackUpgrade"",
                    ""type"": ""Button"",
                    ""id"": ""e2c8dbad-4761-4f5c-b8d4-6e366608965e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueBuildingDefenceUpgrade"",
                    ""type"": ""Button"",
                    ""id"": ""862a3f72-8545-4399-8289-8d74f5a24116"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildCommandCenter"",
                    ""type"": ""Button"",
                    ""id"": ""dc4ba644-0d32-453b-9cb5-e7df31892b72"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildMiningCamp"",
                    ""type"": ""Button"",
                    ""id"": ""7ac2ccc9-2d4d-417f-adc3-06ed52646a1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildBarrack"",
                    ""type"": ""Button"",
                    ""id"": ""448e53db-0dfb-494e-bb4f-c86a15d75b10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildTurret"",
                    ""type"": ""Button"",
                    ""id"": ""e42fd7b4-4f79-4ce4-a5be-88137a9859e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildBuildersLab"",
                    ""type"": ""Button"",
                    ""id"": ""533e48e2-2221-4212-b78a-2026a620c324"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildWarriorsLab"",
                    ""type"": ""Button"",
                    ""id"": ""d59a1101-5d3f-4c8e-ac22-b7ff34d6132f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7bc14984-c2b6-487b-86d6-e75e07f1bb87"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42adb3e4-4981-4f8c-8b12-99072b3ec02d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b204a861-702d-4d64-b2d1-41e6393bdc03"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attach"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5cab03c-b33d-492b-b97a-7d2d1f36f607"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a16c8c89-3d1b-4110-8b09-e36db0849f51"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetIdleStrategy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f46ec94a-57e6-4745-9743-61a0c965119f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetAggressiveStrategy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d38b39-0e43-4656-b2f0-94fbba1a5592"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetDefenciveStrategy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""158dd7c1-412f-4287-86f2-6604efabc895"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueWorkerUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dd39db7-6bce-4191-9ca7-44fb80eaff19"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeWorkers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baa5b49c-2529-4614-a338-6eeb54701a80"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CollectWorkers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c40c78a-c1e0-4850-82d9-c160c2a7b870"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23f5ac76-6d22-4de6-b878-9aeeaaa893ac"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueMeleeWarrior"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11a06f10-c48d-4c29-9dce-daa3670904dc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueRangedWarrior"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4776095a-2aa0-4276-af55-ffc69fc9ada8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueBuildingAttackUpgrade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15104e7d-594a-46c3-85ea-a24ec0015416"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueBuildingDefenceUpgrade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f116a36-e49f-4523-89f4-bb1b9626c488"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildCommandCenter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5933d362-8972-48e5-8a53-b72e0923c560"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildMiningCamp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6942862-e1dd-49e5-bb56-023650cc9405"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildBarrack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db4b47eb-4b29-47ce-98a1-80b88fcaf156"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12e526de-d9d0-439a-a692-63b7b751b7fc"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildBuildersLab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86a82c7e-4eb3-4f99-bcef-8d9bc75f4963"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildWarriorsLab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Groups
        m_Groups = asset.FindActionMap("Groups", throwIfNotFound: true);
        m_Groups_InteractToGroup = m_Groups.FindAction("InteractToGroup", throwIfNotFound: true);
        m_Groups_AddToGroupState = m_Groups.FindAction("AddToGroupState", throwIfNotFound: true);
        m_Groups_SetGroupState = m_Groups.FindAction("SetGroupState", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Pan = m_Camera.FindAction("Pan", throwIfNotFound: true);
        m_Camera_Move = m_Camera.FindAction("Move", throwIfNotFound: true);
        m_Camera_AltState = m_Camera.FindAction("AltState", throwIfNotFound: true);
        // OnScreenInteraction
        m_OnScreenInteraction = asset.FindActionMap("OnScreenInteraction", throwIfNotFound: true);
        m_OnScreenInteraction_BeginDrag = m_OnScreenInteraction.FindAction("BeginDrag", throwIfNotFound: true);
        m_OnScreenInteraction_LeftClick = m_OnScreenInteraction.FindAction("LeftClick", throwIfNotFound: true);
        m_OnScreenInteraction_RightClick = m_OnScreenInteraction.FindAction("RightClick", throwIfNotFound: true);
        m_OnScreenInteraction_MouseMove = m_OnScreenInteraction.FindAction("MouseMove", throwIfNotFound: true);
        m_OnScreenInteraction_ShiftMod = m_OnScreenInteraction.FindAction("ShiftMod", throwIfNotFound: true);
        m_OnScreenInteraction_Drop = m_OnScreenInteraction.FindAction("Drop", throwIfNotFound: true);
        m_OnScreenInteraction_RollGroup = m_OnScreenInteraction.FindAction("RollGroup", throwIfNotFound: true);
        // Bindings
        m_Bindings = asset.FindActionMap("Bindings", throwIfNotFound: true);
        m_Bindings_Move = m_Bindings.FindAction("Move", throwIfNotFound: true);
        m_Bindings_Attack = m_Bindings.FindAction("Attack", throwIfNotFound: true);
        m_Bindings_Attach = m_Bindings.FindAction("Attach", throwIfNotFound: true);
        m_Bindings_OpenBuildMenu = m_Bindings.FindAction("OpenBuildMenu", throwIfNotFound: true);
        m_Bindings_SetIdleStrategy = m_Bindings.FindAction("SetIdleStrategy", throwIfNotFound: true);
        m_Bindings_SetAggressiveStrategy = m_Bindings.FindAction("SetAggressiveStrategy", throwIfNotFound: true);
        m_Bindings_SetDefenciveStrategy = m_Bindings.FindAction("SetDefenciveStrategy", throwIfNotFound: true);
        m_Bindings_QueueWorkerUnit = m_Bindings.FindAction("QueueWorkerUnit", throwIfNotFound: true);
        m_Bindings_FreeWorkers = m_Bindings.FindAction("FreeWorkers", throwIfNotFound: true);
        m_Bindings_CollectWorkers = m_Bindings.FindAction("CollectWorkers", throwIfNotFound: true);
        m_Bindings_Stop = m_Bindings.FindAction("Stop", throwIfNotFound: true);
        m_Bindings_QueueMeleeWarrior = m_Bindings.FindAction("QueueMeleeWarrior", throwIfNotFound: true);
        m_Bindings_QueueRangedWarrior = m_Bindings.FindAction("QueueRangedWarrior", throwIfNotFound: true);
        m_Bindings_QueueBuildingAttackUpgrade = m_Bindings.FindAction("QueueBuildingAttackUpgrade", throwIfNotFound: true);
        m_Bindings_QueueBuildingDefenceUpgrade = m_Bindings.FindAction("QueueBuildingDefenceUpgrade", throwIfNotFound: true);
        m_Bindings_BuildCommandCenter = m_Bindings.FindAction("BuildCommandCenter", throwIfNotFound: true);
        m_Bindings_BuildMiningCamp = m_Bindings.FindAction("BuildMiningCamp", throwIfNotFound: true);
        m_Bindings_BuildBarrack = m_Bindings.FindAction("BuildBarrack", throwIfNotFound: true);
        m_Bindings_BuildTurret = m_Bindings.FindAction("BuildTurret", throwIfNotFound: true);
        m_Bindings_BuildBuildersLab = m_Bindings.FindAction("BuildBuildersLab", throwIfNotFound: true);
        m_Bindings_BuildWarriorsLab = m_Bindings.FindAction("BuildWarriorsLab", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Groups
    private readonly InputActionMap m_Groups;
    private IGroupsActions m_GroupsActionsCallbackInterface;
    private readonly InputAction m_Groups_InteractToGroup;
    private readonly InputAction m_Groups_AddToGroupState;
    private readonly InputAction m_Groups_SetGroupState;
    public struct GroupsActions
    {
        private @RtsInputActions m_Wrapper;
        public GroupsActions(@RtsInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @InteractToGroup => m_Wrapper.m_Groups_InteractToGroup;
        public InputAction @AddToGroupState => m_Wrapper.m_Groups_AddToGroupState;
        public InputAction @SetGroupState => m_Wrapper.m_Groups_SetGroupState;
        public InputActionMap Get() { return m_Wrapper.m_Groups; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GroupsActions set) { return set.Get(); }
        public void SetCallbacks(IGroupsActions instance)
        {
            if (m_Wrapper.m_GroupsActionsCallbackInterface != null)
            {
                @InteractToGroup.started -= m_Wrapper.m_GroupsActionsCallbackInterface.OnInteractToGroup;
                @InteractToGroup.performed -= m_Wrapper.m_GroupsActionsCallbackInterface.OnInteractToGroup;
                @InteractToGroup.canceled -= m_Wrapper.m_GroupsActionsCallbackInterface.OnInteractToGroup;
                @AddToGroupState.started -= m_Wrapper.m_GroupsActionsCallbackInterface.OnAddToGroupState;
                @AddToGroupState.performed -= m_Wrapper.m_GroupsActionsCallbackInterface.OnAddToGroupState;
                @AddToGroupState.canceled -= m_Wrapper.m_GroupsActionsCallbackInterface.OnAddToGroupState;
                @SetGroupState.started -= m_Wrapper.m_GroupsActionsCallbackInterface.OnSetGroupState;
                @SetGroupState.performed -= m_Wrapper.m_GroupsActionsCallbackInterface.OnSetGroupState;
                @SetGroupState.canceled -= m_Wrapper.m_GroupsActionsCallbackInterface.OnSetGroupState;
            }
            m_Wrapper.m_GroupsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @InteractToGroup.started += instance.OnInteractToGroup;
                @InteractToGroup.performed += instance.OnInteractToGroup;
                @InteractToGroup.canceled += instance.OnInteractToGroup;
                @AddToGroupState.started += instance.OnAddToGroupState;
                @AddToGroupState.performed += instance.OnAddToGroupState;
                @AddToGroupState.canceled += instance.OnAddToGroupState;
                @SetGroupState.started += instance.OnSetGroupState;
                @SetGroupState.performed += instance.OnSetGroupState;
                @SetGroupState.canceled += instance.OnSetGroupState;
            }
        }
    }
    public GroupsActions @Groups => new GroupsActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_Pan;
    private readonly InputAction m_Camera_Move;
    private readonly InputAction m_Camera_AltState;
    public struct CameraActions
    {
        private @RtsInputActions m_Wrapper;
        public CameraActions(@RtsInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pan => m_Wrapper.m_Camera_Pan;
        public InputAction @Move => m_Wrapper.m_Camera_Move;
        public InputAction @AltState => m_Wrapper.m_Camera_AltState;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @Pan.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan;
                @Pan.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan;
                @Pan.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan;
                @Move.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMove;
                @AltState.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnAltState;
                @AltState.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnAltState;
                @AltState.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnAltState;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pan.started += instance.OnPan;
                @Pan.performed += instance.OnPan;
                @Pan.canceled += instance.OnPan;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @AltState.started += instance.OnAltState;
                @AltState.performed += instance.OnAltState;
                @AltState.canceled += instance.OnAltState;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // OnScreenInteraction
    private readonly InputActionMap m_OnScreenInteraction;
    private IOnScreenInteractionActions m_OnScreenInteractionActionsCallbackInterface;
    private readonly InputAction m_OnScreenInteraction_BeginDrag;
    private readonly InputAction m_OnScreenInteraction_LeftClick;
    private readonly InputAction m_OnScreenInteraction_RightClick;
    private readonly InputAction m_OnScreenInteraction_MouseMove;
    private readonly InputAction m_OnScreenInteraction_ShiftMod;
    private readonly InputAction m_OnScreenInteraction_Drop;
    private readonly InputAction m_OnScreenInteraction_RollGroup;
    public struct OnScreenInteractionActions
    {
        private @RtsInputActions m_Wrapper;
        public OnScreenInteractionActions(@RtsInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @BeginDrag => m_Wrapper.m_OnScreenInteraction_BeginDrag;
        public InputAction @LeftClick => m_Wrapper.m_OnScreenInteraction_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_OnScreenInteraction_RightClick;
        public InputAction @MouseMove => m_Wrapper.m_OnScreenInteraction_MouseMove;
        public InputAction @ShiftMod => m_Wrapper.m_OnScreenInteraction_ShiftMod;
        public InputAction @Drop => m_Wrapper.m_OnScreenInteraction_Drop;
        public InputAction @RollGroup => m_Wrapper.m_OnScreenInteraction_RollGroup;
        public InputActionMap Get() { return m_Wrapper.m_OnScreenInteraction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnScreenInteractionActions set) { return set.Get(); }
        public void SetCallbacks(IOnScreenInteractionActions instance)
        {
            if (m_Wrapper.m_OnScreenInteractionActionsCallbackInterface != null)
            {
                @BeginDrag.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnBeginDrag;
                @BeginDrag.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnBeginDrag;
                @BeginDrag.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnBeginDrag;
                @LeftClick.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnLeftClick;
                @RightClick.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRightClick;
                @MouseMove.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnMouseMove;
                @MouseMove.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnMouseMove;
                @MouseMove.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnMouseMove;
                @ShiftMod.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnShiftMod;
                @ShiftMod.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnShiftMod;
                @ShiftMod.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnShiftMod;
                @Drop.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnDrop;
                @RollGroup.started -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRollGroup;
                @RollGroup.performed -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRollGroup;
                @RollGroup.canceled -= m_Wrapper.m_OnScreenInteractionActionsCallbackInterface.OnRollGroup;
            }
            m_Wrapper.m_OnScreenInteractionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @BeginDrag.started += instance.OnBeginDrag;
                @BeginDrag.performed += instance.OnBeginDrag;
                @BeginDrag.canceled += instance.OnBeginDrag;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @MouseMove.started += instance.OnMouseMove;
                @MouseMove.performed += instance.OnMouseMove;
                @MouseMove.canceled += instance.OnMouseMove;
                @ShiftMod.started += instance.OnShiftMod;
                @ShiftMod.performed += instance.OnShiftMod;
                @ShiftMod.canceled += instance.OnShiftMod;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
                @RollGroup.started += instance.OnRollGroup;
                @RollGroup.performed += instance.OnRollGroup;
                @RollGroup.canceled += instance.OnRollGroup;
            }
        }
    }
    public OnScreenInteractionActions @OnScreenInteraction => new OnScreenInteractionActions(this);

    // Bindings
    private readonly InputActionMap m_Bindings;
    private IBindingsActions m_BindingsActionsCallbackInterface;
    private readonly InputAction m_Bindings_Move;
    private readonly InputAction m_Bindings_Attack;
    private readonly InputAction m_Bindings_Attach;
    private readonly InputAction m_Bindings_OpenBuildMenu;
    private readonly InputAction m_Bindings_SetIdleStrategy;
    private readonly InputAction m_Bindings_SetAggressiveStrategy;
    private readonly InputAction m_Bindings_SetDefenciveStrategy;
    private readonly InputAction m_Bindings_QueueWorkerUnit;
    private readonly InputAction m_Bindings_FreeWorkers;
    private readonly InputAction m_Bindings_CollectWorkers;
    private readonly InputAction m_Bindings_Stop;
    private readonly InputAction m_Bindings_QueueMeleeWarrior;
    private readonly InputAction m_Bindings_QueueRangedWarrior;
    private readonly InputAction m_Bindings_QueueBuildingAttackUpgrade;
    private readonly InputAction m_Bindings_QueueBuildingDefenceUpgrade;
    private readonly InputAction m_Bindings_BuildCommandCenter;
    private readonly InputAction m_Bindings_BuildMiningCamp;
    private readonly InputAction m_Bindings_BuildBarrack;
    private readonly InputAction m_Bindings_BuildTurret;
    private readonly InputAction m_Bindings_BuildBuildersLab;
    private readonly InputAction m_Bindings_BuildWarriorsLab;
    public struct BindingsActions
    {
        private @RtsInputActions m_Wrapper;
        public BindingsActions(@RtsInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Bindings_Move;
        public InputAction @Attack => m_Wrapper.m_Bindings_Attack;
        public InputAction @Attach => m_Wrapper.m_Bindings_Attach;
        public InputAction @OpenBuildMenu => m_Wrapper.m_Bindings_OpenBuildMenu;
        public InputAction @SetIdleStrategy => m_Wrapper.m_Bindings_SetIdleStrategy;
        public InputAction @SetAggressiveStrategy => m_Wrapper.m_Bindings_SetAggressiveStrategy;
        public InputAction @SetDefenciveStrategy => m_Wrapper.m_Bindings_SetDefenciveStrategy;
        public InputAction @QueueWorkerUnit => m_Wrapper.m_Bindings_QueueWorkerUnit;
        public InputAction @FreeWorkers => m_Wrapper.m_Bindings_FreeWorkers;
        public InputAction @CollectWorkers => m_Wrapper.m_Bindings_CollectWorkers;
        public InputAction @Stop => m_Wrapper.m_Bindings_Stop;
        public InputAction @QueueMeleeWarrior => m_Wrapper.m_Bindings_QueueMeleeWarrior;
        public InputAction @QueueRangedWarrior => m_Wrapper.m_Bindings_QueueRangedWarrior;
        public InputAction @QueueBuildingAttackUpgrade => m_Wrapper.m_Bindings_QueueBuildingAttackUpgrade;
        public InputAction @QueueBuildingDefenceUpgrade => m_Wrapper.m_Bindings_QueueBuildingDefenceUpgrade;
        public InputAction @BuildCommandCenter => m_Wrapper.m_Bindings_BuildCommandCenter;
        public InputAction @BuildMiningCamp => m_Wrapper.m_Bindings_BuildMiningCamp;
        public InputAction @BuildBarrack => m_Wrapper.m_Bindings_BuildBarrack;
        public InputAction @BuildTurret => m_Wrapper.m_Bindings_BuildTurret;
        public InputAction @BuildBuildersLab => m_Wrapper.m_Bindings_BuildBuildersLab;
        public InputAction @BuildWarriorsLab => m_Wrapper.m_Bindings_BuildWarriorsLab;
        public InputActionMap Get() { return m_Wrapper.m_Bindings; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BindingsActions set) { return set.Get(); }
        public void SetCallbacks(IBindingsActions instance)
        {
            if (m_Wrapper.m_BindingsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttack;
                @Attach.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttach;
                @Attach.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttach;
                @Attach.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnAttach;
                @OpenBuildMenu.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnOpenBuildMenu;
                @SetIdleStrategy.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetIdleStrategy;
                @SetIdleStrategy.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetIdleStrategy;
                @SetIdleStrategy.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetIdleStrategy;
                @SetAggressiveStrategy.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetAggressiveStrategy;
                @SetAggressiveStrategy.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetAggressiveStrategy;
                @SetAggressiveStrategy.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetAggressiveStrategy;
                @SetDefenciveStrategy.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetDefenciveStrategy;
                @SetDefenciveStrategy.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetDefenciveStrategy;
                @SetDefenciveStrategy.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnSetDefenciveStrategy;
                @QueueWorkerUnit.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueWorkerUnit;
                @QueueWorkerUnit.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueWorkerUnit;
                @QueueWorkerUnit.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueWorkerUnit;
                @FreeWorkers.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnFreeWorkers;
                @FreeWorkers.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnFreeWorkers;
                @FreeWorkers.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnFreeWorkers;
                @CollectWorkers.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnCollectWorkers;
                @CollectWorkers.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnCollectWorkers;
                @CollectWorkers.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnCollectWorkers;
                @Stop.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnStop;
                @QueueMeleeWarrior.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueMeleeWarrior;
                @QueueMeleeWarrior.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueMeleeWarrior;
                @QueueMeleeWarrior.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueMeleeWarrior;
                @QueueRangedWarrior.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueRangedWarrior;
                @QueueRangedWarrior.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueRangedWarrior;
                @QueueRangedWarrior.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueRangedWarrior;
                @QueueBuildingAttackUpgrade.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingAttackUpgrade;
                @QueueBuildingAttackUpgrade.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingAttackUpgrade;
                @QueueBuildingAttackUpgrade.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingAttackUpgrade;
                @QueueBuildingDefenceUpgrade.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingDefenceUpgrade;
                @QueueBuildingDefenceUpgrade.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingDefenceUpgrade;
                @QueueBuildingDefenceUpgrade.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnQueueBuildingDefenceUpgrade;
                @BuildCommandCenter.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildCommandCenter;
                @BuildCommandCenter.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildCommandCenter;
                @BuildCommandCenter.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildCommandCenter;
                @BuildMiningCamp.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildMiningCamp;
                @BuildMiningCamp.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildMiningCamp;
                @BuildMiningCamp.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildMiningCamp;
                @BuildBarrack.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBarrack;
                @BuildBarrack.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBarrack;
                @BuildBarrack.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBarrack;
                @BuildTurret.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildTurret;
                @BuildTurret.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildTurret;
                @BuildTurret.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildTurret;
                @BuildBuildersLab.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBuildersLab;
                @BuildBuildersLab.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBuildersLab;
                @BuildBuildersLab.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildBuildersLab;
                @BuildWarriorsLab.started -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildWarriorsLab;
                @BuildWarriorsLab.performed -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildWarriorsLab;
                @BuildWarriorsLab.canceled -= m_Wrapper.m_BindingsActionsCallbackInterface.OnBuildWarriorsLab;
            }
            m_Wrapper.m_BindingsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Attach.started += instance.OnAttach;
                @Attach.performed += instance.OnAttach;
                @Attach.canceled += instance.OnAttach;
                @OpenBuildMenu.started += instance.OnOpenBuildMenu;
                @OpenBuildMenu.performed += instance.OnOpenBuildMenu;
                @OpenBuildMenu.canceled += instance.OnOpenBuildMenu;
                @SetIdleStrategy.started += instance.OnSetIdleStrategy;
                @SetIdleStrategy.performed += instance.OnSetIdleStrategy;
                @SetIdleStrategy.canceled += instance.OnSetIdleStrategy;
                @SetAggressiveStrategy.started += instance.OnSetAggressiveStrategy;
                @SetAggressiveStrategy.performed += instance.OnSetAggressiveStrategy;
                @SetAggressiveStrategy.canceled += instance.OnSetAggressiveStrategy;
                @SetDefenciveStrategy.started += instance.OnSetDefenciveStrategy;
                @SetDefenciveStrategy.performed += instance.OnSetDefenciveStrategy;
                @SetDefenciveStrategy.canceled += instance.OnSetDefenciveStrategy;
                @QueueWorkerUnit.started += instance.OnQueueWorkerUnit;
                @QueueWorkerUnit.performed += instance.OnQueueWorkerUnit;
                @QueueWorkerUnit.canceled += instance.OnQueueWorkerUnit;
                @FreeWorkers.started += instance.OnFreeWorkers;
                @FreeWorkers.performed += instance.OnFreeWorkers;
                @FreeWorkers.canceled += instance.OnFreeWorkers;
                @CollectWorkers.started += instance.OnCollectWorkers;
                @CollectWorkers.performed += instance.OnCollectWorkers;
                @CollectWorkers.canceled += instance.OnCollectWorkers;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @QueueMeleeWarrior.started += instance.OnQueueMeleeWarrior;
                @QueueMeleeWarrior.performed += instance.OnQueueMeleeWarrior;
                @QueueMeleeWarrior.canceled += instance.OnQueueMeleeWarrior;
                @QueueRangedWarrior.started += instance.OnQueueRangedWarrior;
                @QueueRangedWarrior.performed += instance.OnQueueRangedWarrior;
                @QueueRangedWarrior.canceled += instance.OnQueueRangedWarrior;
                @QueueBuildingAttackUpgrade.started += instance.OnQueueBuildingAttackUpgrade;
                @QueueBuildingAttackUpgrade.performed += instance.OnQueueBuildingAttackUpgrade;
                @QueueBuildingAttackUpgrade.canceled += instance.OnQueueBuildingAttackUpgrade;
                @QueueBuildingDefenceUpgrade.started += instance.OnQueueBuildingDefenceUpgrade;
                @QueueBuildingDefenceUpgrade.performed += instance.OnQueueBuildingDefenceUpgrade;
                @QueueBuildingDefenceUpgrade.canceled += instance.OnQueueBuildingDefenceUpgrade;
                @BuildCommandCenter.started += instance.OnBuildCommandCenter;
                @BuildCommandCenter.performed += instance.OnBuildCommandCenter;
                @BuildCommandCenter.canceled += instance.OnBuildCommandCenter;
                @BuildMiningCamp.started += instance.OnBuildMiningCamp;
                @BuildMiningCamp.performed += instance.OnBuildMiningCamp;
                @BuildMiningCamp.canceled += instance.OnBuildMiningCamp;
                @BuildBarrack.started += instance.OnBuildBarrack;
                @BuildBarrack.performed += instance.OnBuildBarrack;
                @BuildBarrack.canceled += instance.OnBuildBarrack;
                @BuildTurret.started += instance.OnBuildTurret;
                @BuildTurret.performed += instance.OnBuildTurret;
                @BuildTurret.canceled += instance.OnBuildTurret;
                @BuildBuildersLab.started += instance.OnBuildBuildersLab;
                @BuildBuildersLab.performed += instance.OnBuildBuildersLab;
                @BuildBuildersLab.canceled += instance.OnBuildBuildersLab;
                @BuildWarriorsLab.started += instance.OnBuildWarriorsLab;
                @BuildWarriorsLab.performed += instance.OnBuildWarriorsLab;
                @BuildWarriorsLab.canceled += instance.OnBuildWarriorsLab;
            }
        }
    }
    public BindingsActions @Bindings => new BindingsActions(this);
    public interface IGroupsActions
    {
        void OnInteractToGroup(InputAction.CallbackContext context);
        void OnAddToGroupState(InputAction.CallbackContext context);
        void OnSetGroupState(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnPan(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnAltState(InputAction.CallbackContext context);
    }
    public interface IOnScreenInteractionActions
    {
        void OnBeginDrag(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnMouseMove(InputAction.CallbackContext context);
        void OnShiftMod(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnRollGroup(InputAction.CallbackContext context);
    }
    public interface IBindingsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnAttach(InputAction.CallbackContext context);
        void OnOpenBuildMenu(InputAction.CallbackContext context);
        void OnSetIdleStrategy(InputAction.CallbackContext context);
        void OnSetAggressiveStrategy(InputAction.CallbackContext context);
        void OnSetDefenciveStrategy(InputAction.CallbackContext context);
        void OnQueueWorkerUnit(InputAction.CallbackContext context);
        void OnFreeWorkers(InputAction.CallbackContext context);
        void OnCollectWorkers(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnQueueMeleeWarrior(InputAction.CallbackContext context);
        void OnQueueRangedWarrior(InputAction.CallbackContext context);
        void OnQueueBuildingAttackUpgrade(InputAction.CallbackContext context);
        void OnQueueBuildingDefenceUpgrade(InputAction.CallbackContext context);
        void OnBuildCommandCenter(InputAction.CallbackContext context);
        void OnBuildMiningCamp(InputAction.CallbackContext context);
        void OnBuildBarrack(InputAction.CallbackContext context);
        void OnBuildTurret(InputAction.CallbackContext context);
        void OnBuildBuildersLab(InputAction.CallbackContext context);
        void OnBuildWarriorsLab(InputAction.CallbackContext context);
    }
}
