using System.Collections.Generic;
using UnityEditor;

namespace TelroshanTools.BuildSettingsPresets.Editor
{
    public static class BuildSettingsPresetsMenuItems
    {
        /// <summary>
        /// Guid => preset name
        /// </summary>
        public static readonly Dictionary<string, string> Presets = new Dictionary<string, string>
        {
            // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there

            #region GeneratedPresets

			{"6fe4d4826d6e04b45a67ccb7ee46e1aa", "Debug"},
			{"d42ad8b01c8a68846865607ee58cdd0e", "Default"},
			{"53d68ea13bd3ea44581af27004f2a10b", "Play"},

            #endregion
        };

        // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there

        #region GeneratedMenuItems

		[MenuItem("Build presets/Debug")]
		public static void Apply6fe4d4826d6e04b45a67ccb7ee46e1aa()
		{
			BuildSettingsPresetsManager.ApplyPreset("6fe4d4826d6e04b45a67ccb7ee46e1aa");
		}

		[MenuItem("Build presets/Default")]
		public static void Applyd42ad8b01c8a68846865607ee58cdd0e()
		{
			BuildSettingsPresetsManager.ApplyPreset("d42ad8b01c8a68846865607ee58cdd0e");
		}

		[MenuItem("Build presets/Play")]
		public static void Apply53d68ea13bd3ea44581af27004f2a10b()
		{
			BuildSettingsPresetsManager.ApplyPreset("53d68ea13bd3ea44581af27004f2a10b");
		}

        #endregion
    }
}
